server:
  port: 8080

zuul:
  routes:
    #路由别名，无其他意义
    auth-center:
      path: /login/**
      url: http://127.0.0.1:8081/
      #sensitiveHeaders配置会过滤客户端附带的headers cookie 不会传递给下游服务
      sensitiveHeaders: Cookie,Set-Cookie
      stripPrefix: false
    backend-service:
      path: /backend/**
      url: http://127.0.0.1:8082/

zhph.security.jwt.secret: otherpeopledontknowit


