server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
#    data: classpath:db/data.sql
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
logging:
  level: debug

zhph.security.jwt.secret: otherpeopledontknowit
